### ISSUE TITLE
go get returns an error

### ISSUE THREAD

**Issue by sim4life** [anthonynsimon/bild#13]
Doing go get returns the error:
can't load package: package github.com/anthonynsimon/bild: no buildable Go source files in $GOPATH/src/github.com/anthonynsimon/bild

**Comment by anthonynsimon** [comment]
This is because the project was recently restructured into sub-packages. The repo itself has no go files at the root right now. To use the functions you should get the project via:

`go get github.com/anthonynsimon/bild/...` 

Notice the '...' at the end, this is to signify that you want all the packages on that repo.

And then in your code import the specific package that you want to use, for example gaussian blur:

```
package main

import "github.com/anthonynsimon/bild/blur"

func main() {
    result := blur.Gaussian(img, 3.0)
}
```

I will update the README to clarify on this. Thank you for reporting it.
